WINDOW_X = 800
WINDOW_Y = 700
TOP_X,TOP_Y = WINDOW_X / 20,WINDOW_Y / 20
BOTTOM_X,BOTTOM_Y = TOP_X / 10,TOP_Y / 10

CENTER_X = WINDOW_X - TOP_X - BOTTOM_X
CENTER_Y = WINDOW_Y - TOP_Y - BOTTOM_Y - 100
# print TOP_X,TOP_Y
print CENTER_X,CENTER_Y
